"use client";

export default function Footer() {
  return (
    <div className="w-full bg-[#EFFAF5] p-4 mt-6">
      <div className="flex justify-around items-center text-[#6AAF23] text-lg font-medium">
        <span>Generated by Biota Nutri Calculator</span>
        <span>Generated on: 19 Aug 2025</span>
        <span>Language: English</span>
      </div>
    </div>
  );
}
